### ISSUE TITLE
Bertanya

### ISSUE THREAD

**Issue by aryagustiana101** [juankhusuma/backend-final-secs-2022#5]
Halo Kak perkenalkan saya Arya.
Saya mau bertanya untuk SECS 2022 ini apakah sudah ada pengumuman pemenangnya Kak? Apakah Kakak menang?
Terimakasih sudah meluangkan waktu untuk menjawab pertanyaan saya Kak.

**Comment by juankhusuma** [comment]
Maaf ya Arya saya baru baca pesan ini di GitHub :(

**Comment by aryagustiana101** [comment]
Tidak masalah Kak, jadi bagaimana untuk jawaban dari pertanyaan saya?
